[project]
name = "assignment-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.3.0",
    "datasets>=3.2.0",
    "evaluate>=0.4.3",
    "scikit-learn>=1.6.1",
    "transformers>=4.48.3",
]
